// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTask(arg1, arg2) {
  return window['go']['wailsbridge']['WailsBridge']['DeleteTask'](arg1, arg2);
}

export function GetApplicationConfig() {
  return window['go']['wailsbridge']['WailsBridge']['GetApplicationConfig']();
}

export function GetTasks() {
  return window['go']['wailsbridge']['WailsBridge']['GetTasks']();
}

export function OnStartup(arg1) {
  return window['go']['wailsbridge']['WailsBridge']['OnStartup'](arg1);
}

export function SaveApplicationConfig(arg1) {
  return window['go']['wailsbridge']['WailsBridge']['SaveApplicationConfig'](arg1);
}

export function ToggleTaskPauseState(arg1) {
  return window['go']['wailsbridge']['WailsBridge']['ToggleTaskPauseState'](arg1);
}

export function TriggerNewDownload(arg1) {
  return window['go']['wailsbridge']['WailsBridge']['TriggerNewDownload'](arg1);
}
