// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {task} from '../models';
import {context} from '../models';

export function DeleteTask(arg1:string,arg2:boolean):Promise<void>;

export function GetApplicationConfig():Promise<config.AppConfig>;

export function GetTasks():Promise<Array<task.Task>>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function SaveApplicationConfig(arg1:config.AppConfig):Promise<void>;

export function ToggleTaskPauseState(arg1:string):Promise<void>;

export function TriggerNewDownload(arg1:string):Promise<task.Task>;
