// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {task} from '../models';

export function GetApplicationConfig():Promise<config.AppConfig>;

export function SaveApplicationConfig(arg1:config.AppConfig):Promise<void>;

export function ToggleTaskPauseState(arg1:string):Promise<void>;

export function TriggerNewDownload(arg1:string):Promise<task.Task>;
